import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.List;

public class Interface extends javax.swing.JFrame {
        Path path = Paths.get("C:/Users/flima/Documents/NetBeansProjects/TavernaMedieval/log.txt");//caminho utilizado para fazer append no log
        Atendente a = new Atendente("jonas", 123456798, 1.2f);//somente um atendente para facilitar
        Cliente cliente[] = new Cliente[10];//cria um aray de clientes
        JCheckBox itens[] = new JCheckBox[30];//cria o array do menu
        JTextField qtd[] = new JTextField[30];//cria array da qtd de item pedidos do menu
        float valor[] = {15, 59.90f, 55.49f, 2.99f, 5, 6.50f, 10, 19.90f, 8.99f, 10,
                        6, 7, 3, 1.99f, 3.99f, 12, 7, 20, 20, 50,
                        14.90f, 68.90f, 114.98f, 14.99f, 15.9f, 59.97f, 20, 73.45f, 69,93, 12.99f};//esses são os preços dos itens do menu
        String menorMsg = "Cliente menor de idade\nNão é possivel adicionar alcólicos";
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCadastrar = new javax.swing.JButton();
        buttonPedido = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        comandaCadastro = new javax.swing.JComboBox<>();
        especies = new javax.swing.JComboBox<>();
        buttonCadastro = new javax.swing.JButton();
        cpf = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        ano = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fazerPedido = new javax.swing.JButton();
        encerrarConta = new javax.swing.JButton();
        comandaPedido = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        buttonPedido.setText("Pedido");
        buttonPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\flima\\Documents\\FlatLAF\\paper2.jpg")); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comandaCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comanda 1", "Comanda 2", "Comanda 3", "Comanda 4", "Comanda 5", "Comanda 6", "Comanda 7", "Comanda 8", "Comanda 9", "Comanda 10" }));
        jPanel1.add(comandaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 22, 270, 60));

        especies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anao", "Centauro", "Draconato", "Elfo", "Goblin", "Humano", "Kobold", "Orc" }));
        jPanel1.add(especies, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 610, 60));

        buttonCadastro.setText("Cadastrar");
        buttonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 130, 60));
        jPanel1.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 610, 60));

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 610, 60));
        jPanel1.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 140, 60));
        jPanel1.add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 140, 60));
        jPanel1.add(ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 140, 60));

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Edwardian Script ITC", 0, 72)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("CSC");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, 60));

        jLabel5.setFont(new java.awt.Font("Old English Text MT", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Comanda");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 60));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Edwardian Script ITC", 0, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Nome ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 60));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Edwardian Script ITC", 0, 72)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Especie");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 180, 60));

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Edwardian Script ITC", 0, 72)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Nascimento");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 250, 40));

        jLabel7.setFont(new java.awt.Font("Edwardian Script ITC", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("(Cadastro de ser consiente)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, 30));

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("  /");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 70, 70));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText(" /");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 70, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\flima\\Documents\\FlatLAF\\paper.jpg")); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 690));

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fazerPedido.setText("Fazer Pedido");
        fazerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazerPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(fazerPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 160, 30));

        encerrarConta.setText("Encerrar Conta");
        encerrarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerrarContaActionPerformed(evt);
            }
        });
        jPanel2.add(encerrarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, 160, 30));

        comandaPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comanda 1", "Comanda 2", "Comanda 3", "Comanda 4", "Comanda 5", "Comanda 6", "Comanda 7", "Comanda 8", "Comanda 9", "Comanda 10" }));
        jPanel2.add(comandaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 22, 270, 60));

        jLabel15.setFont(new java.awt.Font("Old English Text MT", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Comanda");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 60));

        jLabel14.setFont(new java.awt.Font("Edwardian Script ITC", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Qtd");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 70, -1));

        jLabel17.setFont(new java.awt.Font("Edwardian Script ITC", 0, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Comidas");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 100, 40));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 100, 40));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 100, 40));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 100, 40));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 100, 40));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 100, 40));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 100, 40));
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 100, 40));
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 100, 40));
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, 100, 40));

        jCheckBox1.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Bolinhos de Gengibre");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 40));

        jCheckBox2.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setText("Roda de Queijo de cabra");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 40));

        jCheckBox3.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox3.setText("Risoto de carangueijo");
        jPanel2.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 40));

        jCheckBox4.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox4.setText("Cogumelos");
        jPanel2.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 40));

        jCheckBox5.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox5.setText("Frutas Wumpa");
        jPanel2.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 40));

        jCheckBox6.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox6.setText("Pukepuff");
        jPanel2.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 40));

        jCheckBox7.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox7.setText("Ambrosia");
        jPanel2.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 40));

        jCheckBox8.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox8.setText("Ração de Nuka-Cola");
        jPanel2.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, 40));

        jCheckBox9.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox9.setText("Pudim de Sobremesa");
        jPanel2.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, 40));

        jCheckBox10.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox10.setText("Biscoitos de Ferro");
        jPanel2.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, 40));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 100, 40));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 100, 40));
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 100, 40));
        jPanel2.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 100, 40));
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 100, 40));

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 100, 40));
        jPanel2.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 100, 40));
        jPanel2.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 100, 40));

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 100, 40));
        jPanel2.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 630, 100, 40));

        jCheckBox11.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox11.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox11.setText("Nuka-Cola");
        jPanel2.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, 40));

        jCheckBox12.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox12.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox12.setText("Suco de Hidra");
        jPanel2.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 40));

        jCheckBox13.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox13.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox13.setText("Água");
        jPanel2.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, 40));

        jCheckBox14.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox14.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox14.setText("Café");
        jPanel2.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, 40));

        jCheckBox15.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox15.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox15.setText("Leite");
        jPanel2.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, 40));

        jCheckBox16.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox16.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox16.setText("Cerveja Amanteigada");
        jPanel2.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, 40));

        jCheckBox17.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox17.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox17.setText("Suco de Uva");
        jPanel2.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, 40));

        jCheckBox18.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox18.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox18.setText("Poção de invisibilidade");
        jPanel2.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, 40));

        jCheckBox19.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox19.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox19.setText("Poção de Energia");
        jPanel2.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, -1, 40));

        jCheckBox20.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox20.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox20.setText("Poção de Vida");
        jPanel2.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, -1, 40));
        jPanel2.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 100, 40));
        jPanel2.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 100, 40));
        jPanel2.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 100, 40));
        jPanel2.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 330, 100, 40));
        jPanel2.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 380, 100, 40));
        jPanel2.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 100, 40));
        jPanel2.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, 100, 40));
        jPanel2.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, 100, 40));
        jPanel2.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, 100, 40));
        jPanel2.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 630, 100, 40));

        jCheckBox21.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox21.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox21.setText("Cerveja");
        jPanel2.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, 40));

        jCheckBox22.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox22.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox22.setText("Vinho");
        jPanel2.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, -1, 40));

        jCheckBox23.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox23.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox23.setText("Hidromel");
        jPanel2.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, 40));

        jCheckBox24.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox24.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox24.setText("Cidra");
        jPanel2.add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, 40));

        jCheckBox25.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox25.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox25.setText("Pale Ale");
        jPanel2.add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, 40));

        jCheckBox26.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox26.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox26.setText("Rum do Caribe");
        jPanel2.add(jCheckBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, -1, 40));

        jCheckBox27.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox27.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox27.setText("Grogue");
        jPanel2.add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, 40));

        jCheckBox28.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox28.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox28.setText("Absinto");
        jPanel2.add(jCheckBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, -1, 40));

        jCheckBox29.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox29.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox29.setText("Licor de Fogo");
        jPanel2.add(jCheckBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 580, -1, 40));

        jCheckBox30.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        jCheckBox30.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox30.setText("Pina Colada");
        jPanel2.add(jCheckBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, -1, 40));

        jLabel18.setFont(new java.awt.Font("Edwardian Script ITC", 0, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Bebidas");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 170, -1));

        jLabel19.setFont(new java.awt.Font("Edwardian Script ITC", 0, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Qtd");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 70, -1));

        jLabel20.setFont(new java.awt.Font("Edwardian Script ITC", 0, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Alcolicos");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 170, -1));

        jLabel21.setFont(new java.awt.Font("Edwardian Script ITC", 0, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Qtd");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 70, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\flima\\Documents\\FlatLAF\\paper.jpg")); // NOI18N
        jLabel16.setText("jLabel12");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 690));

        jTabbedPane1.addTab("tab2", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1090, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void buttonPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPedidoActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_buttonPedidoActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void buttonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastroActionPerformed
        String s = especies.getSelectedItem().toString();
        cliente[comandaCadastro.getSelectedIndex()] = new Cliente(nome.getText(),Long.parseLong(cpf.getText()),s ,
            Integer.parseInt(dia.getText()), Integer.parseInt(mes.getText()), Integer.parseInt(ano.getText()));
        cliente[comandaCadastro.getSelectedIndex()].setEspecie(s);
        
        /*
        o que ocorre abaixo é o metodo que consegui dar append no log. 
        esse bloco ira se repetir algumas vezes durante o codigo
        basicamente "content" é a msg do log e Files.write faz o resto da magia 
        */
        String content = "\nCadastro criado";
        try {
            Files.write(path, content.getBytes(), StandardOpenOption.CREATE, StandardOpenOption.APPEND);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println(cliente[6]);//só pra verificar se a comanda certa foi cadastrada
        System.out.println(cliente[comandaCadastro.getSelectedIndex()]);
        System.out.println("Comanda:" + comandaCadastro.getSelectedIndex()+ " " + comandaCadastro.getItemAt(comandaCadastro.getSelectedIndex()));
        JOptionPane.showMessageDialog(null, "Cliente cadastrado");

    }//GEN-LAST:event_buttonCadastroActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void fazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazerPedidoActionPerformed
        JCheckBox itens[] = {jCheckBox1, jCheckBox2, jCheckBox3, jCheckBox4, jCheckBox5, jCheckBox6, jCheckBox7, jCheckBox8, jCheckBox9, jCheckBox10,
                     jCheckBox11, jCheckBox12, jCheckBox13, jCheckBox14, jCheckBox15, jCheckBox16, jCheckBox17, jCheckBox18, jCheckBox19, jCheckBox20,
                     jCheckBox21, jCheckBox22, jCheckBox23, jCheckBox24, jCheckBox25, jCheckBox26, jCheckBox27, jCheckBox28, jCheckBox29, jCheckBox30};
        JTextField[] qtd = {jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7, jTextField8, jTextField9, jTextField10,
                     jTextField11, jTextField12, jTextField13, jTextField14, jTextField15, jTextField16, jTextField17, jTextField18, jTextField19, jTextField20,
                     jTextField21, jTextField22, jTextField23, jTextField24, jTextField25, jTextField26, jTextField27, jTextField28, jTextField29, jTextField30};
        
        for (int n = 0; n<20; n++){
            if (itens[n].isSelected()){
                cliente[comandaPedido.getSelectedIndex()].setConta(valor[n]*Integer.parseInt(qtd[n].getText()));
            }
        }
        
        String content1 = "\nPedido realizado";
        String content2 = "\nAlcool negado";
        try {
            Files.write(path, content1.getBytes(), StandardOpenOption.CREATE, StandardOpenOption.APPEND);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println(cliente[0]);
        for (int n = 20;n<30;n++){
            if (!cliente[comandaPedido.getSelectedIndex()].ehMaior() && itens[n].isSelected()){
                JOptionPane.showMessageDialog(null, menorMsg);
                try {
                    Files.write(path, content2.getBytes(), StandardOpenOption.CREATE, StandardOpenOption.APPEND);
                } catch (Exception e) {
                e.printStackTrace();
                }
            }
            else if (itens[n].isSelected()){
                
                cliente[comandaPedido.getSelectedIndex()].setConta(valor[n]*Integer.parseInt(qtd[n].getText()));
            }
        }
    }//GEN-LAST:event_fazerPedidoActionPerformed

    private void encerrarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarContaActionPerformed
        float value = cliente[comandaPedido.getSelectedIndex()].getConta()*a.getTaxa();
        cliente[comandaPedido.getSelectedIndex()].setConta(value);
        /*esse metodo serve para finalizar a conta
        settando o valor final de todos os pedidos + a "gorjeta" do atendente
        */
        String s = String.valueOf(value);
        JOptionPane.showMessageDialog(null, s);
        
        String finalizando = "\n Finalizando uma comanda";
        try {
            Files.write(path, finalizando.getBytes(), StandardOpenOption.CREATE, StandardOpenOption.APPEND);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_encerrarContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try{
        FileWriter log = new FileWriter("log.txt");//Cria o arquivo
            log.write("Iniciando o Log");//Escreve o que vc quer
            log.append("\nPrograma iniciado");//adiciona ao arquivo
            log.close();//fecha o arquivo
        }catch(FileNotFoundException e){
            System.out.println("Erro na leitura");
        }catch(IOException e){
            System.out.println("Erro na escrita");
        }
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonCadastro;
    private javax.swing.JButton buttonPedido;
    private javax.swing.JComboBox<String> comandaCadastro;
    private javax.swing.JComboBox<String> comandaPedido;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField dia;
    private javax.swing.JButton encerrarConta;
    private javax.swing.JComboBox<String> especies;
    private javax.swing.JButton fazerPedido;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField mes;
    private javax.swing.JTextField nome;
    // End of variables declaration//GEN-END:variables

    private void JOptionPane(String menorMsg) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
